apiVersion: apps/v1
kind: Deployment
metadata:
  name: priv-reg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priv-reg
  template:
    metadata:
      labels:
        app: priv-reg
    spec:
      containers:
      - name: priv-reg
        image: gcr.io/trustworthy-modules-2/my-app:latest
        ports:
        - containerPort: 3000
