import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

// import { api } from "~/utils/api";

// TODO: add footer w names, proj desc,

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative mt-20">
        <div className="mx-auto max-w-7xl">
          <div className="relative z-10 w-full max-w-2xl pb-28">
            <div className="relative px-4 pt-6 sm:px-6 lg:px-8"></div>

            <main className="mx-auto mt-20 max-w-7xl px-8 sm:mt-12 ">
              <div className="text-left">
                <h1 className=" text-6xl font-bold tracking-tight">
                  <div className="block">ECE 461</div>
                  <div className="block text-blue-600">Trustworthy Modules</div>
                </h1>
                <p className="mt-3 text-xl text-white lg:mx-0">
                  An NPM like package registry
                </p>
                <div className="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start">
                  <div className="rounded-md shadow">
                    <a
                      href="/account"
                      className="flex w-full items-center justify-center rounded-md bg-blue-600 px-8 py-3 text-base font-medium hover:bg-blue-700"
                    >
                      Get Started
                    </a>
                  </div>
                </div>
              </div>
            </main>
          </div>
        </div>
        <div className="absolute inset-y-0 right-0 w-1/2">
          <img className="h-full w-full object-cover" src="" alt="" />
        </div>
      </div>
    </>
  );
};

export default Home;
