import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
// import { signIn, signOut, useSession } from "next-auth/react";

// import { api } from "~/utils/api";
import { signIn } from "next-auth/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-8xl">Home</h1>
        <p className="text-5xl">Trustworthy modules team 9 ece 461</p>
        <div>
          <button onClick={() => void signIn()} className="bg-slate rounded-md">
            Sign in
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
