import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

// import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-8xl">Home</h1>
        {status === "authenticated" && (
          <div className="text-red-600">{session.user.name}</div>
        )}
        <p className="text-5xl">Trustworthy modules team 9 ece 461</p>
        <div>
          <button
            onClick={() => {
              if (status === "authenticated") {
                void signOut();
              } else {
                void signIn();
              }
            }}
            className="bg-slate rounded-md"
          >
            {status === "authenticated" ? "Sign out" : "Sign in"}
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
